### ISSUE TITLE
Page title is still in English

### ISSUE THREAD

**Issue by tesseralis** [reactjs/ja.reactjs.org#168]
Not sure if this is also intentional, but the page title on my browser is still in English:

<img width="208" alt="Screen Shot 2019-03-12 at 7 41 42 PM" src="https://user-images.githubusercontent.com/1278991/54249852-ecfe9500-44fe-11e9-883f-4bbca93bb367.png">

**Comment by smikitky** [comment]
Thank you, I'll fix that
