### ISSUE TITLE
Setting up CI and test site

### ISSUE THREAD

**Issue by koba04** [reactjs/ja.reactjs.org#17]
Currently, CircleCI doesn't run for PRs from fork repositories, so I enabled the setting.
If it doesn't cause any problems, I'd like to require status checks to pass before merging.

In addition to that, Is it helpful to enable deploy preview using Neflify like `reactjs/reactjs.org`?

**Comment by smikitky** [comment]
CI for PRs is working very well, so I think requiring the green status is fine.

I know nothing about the official deploying process, but setting up an independent test site on Netlify does not "pollute" the codebase and has no side effects, right?

**Comment by koba04** [comment]
I've enabled the setting so now passing CircleCI check is required to merge PRs.

> I know nothing about the official deploying process, but setting up an independent test site on Netlify does not "pollute" the codebase and has no side effects, right?

Yes, I assume that it only has to create settings on Netlify, which doesn't affect the codebase.
I'll work on that.

**Comment by koba04** [comment]
@tesseralis 👆 What about this?

**Comment by koba04** [comment]
Netlify integration has been enabled so I close this.
