### ISSUE TITLE
日本語切り替えを押すとトップページに飛ばされる

### ISSUE THREAD

**Issue by YIPG** [reactjs/ja.reactjs.org#194]
現状、言語切替を押すとトップページに飛ばされるので、項目を探し直さなければならず二度手間です。

**Comment by potato4d** [comment]
https://ja.reactjs.org/languages は別ページなので、前のページを探す。みたいなストーリーは実現しづらそうです。ドロップダウンになっていれば別ではあるのですが。

日本語ドキュメントでは基本的に翻訳以外は本家に追従しておきたいので、もし必要であれば本家( https://github.com/reactjs/reactjs.org ) に Issue を作成いただけますか？

**Comment by smikitky** [comment]
こちらは確かにそういう機能が欲しいのですが、本家 reactjs.org のリポジトリで対応しないといけない案件です（日本語版でだけこのUIに独自パッチ当てたとしても、日本語**から**他の言語に飛ぶ時にしか機能しません…）。

https://github.com/reactjs/reactjs.org/issues/1772

こちらで既にIssueが上がっていましたので、とりあえず :+1: してあげてください。

**Comment by smikitky** [comment]
MDNやWikipediaがそうなっていますが、普通はそれぞれの記事について、翻訳が存在する言語のみがドロップダウンには現れるものです。が、reactjs.orgの場合、そもそもどの言語でどの記事が翻訳済みなのかどうかを中央管理しているデータがないので、これが実現しづらそうです。

「ドロップダウンを押して言語を切り替えたつもりがやっぱり英語のページが表示されて残念or混乱」みたいなことにならないためにはどうしたらいいんでしょう。

@potato4d Vue.js側でどうなっているかご存知ですか？　ぱっと見た感じ、今は全言語で全文が翻訳済みだから問題なさそうですが、以前は、例えば「中文」をクリックしたのにリンク先がまだ英語、みたいな事態は存在したのでしょうか。

**Comment by potato4d** [comment]
@smikity
Vue.js のドキュメントは基本的にはコミュニティに決定が委ねられていますが、日本語の場合をご紹介します。

まず英文を全部コピーしてくる。その上で冒頭に「Under construction」の文字とともに、「翻訳中であるため一部英語である」旨を付け加えます。

この段階では、日本語にアクセスしても上記と英文が表示されます。

その後、長いページであればセクションごと、通常のページであればページごとに PR が送られ、翻訳できた時点で冒頭のコメントを削除します。

できる範囲のコンテンツは最大限見てもらうため、この状態を許容して進めています。
