### ISSUE TITLE
Translate glossary

### ISSUE THREAD

**Issue by tesseralis** [reactjs/ja.reactjs.org#2]

**Comment by smikitky** [comment]
In fact, I wasn't aware of the JTF guideline until yesterday. Looks like JTF has two rules that clearly conflicts with Vue's rule (I prefer Vue's rule, though):

> 5. カタカナ語の語尾の長音は省略しない。
> 10. 半角文字と全角文字の間に半角スペースを入れない

**Comment by potato4d** [comment]
The reason for conflicts is that the Vue Community has customized the rules.

And that is described in this part of the document.

https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md#%E7%BF%BB%E8%A8%B3%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB

> Some customization rules for Vue.js official website

I also think that Vue's style is desirable, so I would like to incorporate it.

@smikitky
I will submit a Pull Request to add CONTRIBUTING.md tonight.

Will not you discuss with it using Review Comment?

**Comment by tesseralis** [comment]
We should start a "style guide" page in the wiki with what we decide, even if it's just "use the same rules as vue".

**Comment by smikitky** [comment]
Okay, I think we can use textlint and that `.textlintrc`.

@potato4d I feel Japanese-specific style rules (e.g. 長音符) should live on Wiki rather than `CONTRIBUTIONG.md`, as @tesseralis suggests?

**Comment by tesseralis** [comment]
My main concern is that the repo should reflect the main react one as much as possible (e.g. we might want to copy over that version of CONTRIBUTING.md) in the future. Also we're still in the early stages and deciding what rules we want to follow so it makes more sense to keep it in a wiki.

**Comment by tesseralis** [comment]
Ooh textlint is cool. I can recommend that to the other translations as well and maybe the english version as well hehe...

**Comment by smikitky** [comment]
For the meantime, let me use this translation for "boxed" text:

- Tip → ヒント
- Note → 補足
- Warning → 警告

**Comment by potato4d** [comment]
@tesseralis @smikitky 

React thinks that it is better to make CONTRIBUTING.md of React.
Then, let's merge it with the one of @smikitky's gist, incorporating Vue's example as an example!

**Comment by tesseralis** [comment]
@potato4d @smikitky @koba04 I added a TRANSLATION.md file to each of the forks to serve as a general language guideline.
