### ISSUE TITLE
Create reactjs/textlint-checker-for-react-jp-docs

### ISSUE THREAD

**Issue by potato4d** [reactjs/ja.reactjs.org#20]
I would like to create a repository for the dedicated TextLint rule package "reactjs/textlint-checker-for-react-jp-docs".

That will contribute to improving the quality of future translations.

But, we have other higher priority tasks.
Although this work may not be possible now,let's first write down the rules necessary for this Issue.

**Comment by smikitky** [comment]
I found that textlint can import locally-defined rules via `--rulesdir` option, so maintaining a separate package may not be necessary.

```json
"scripts": {
  "lint:text": "textlint --rulesdir=./textlint content/{docs,home,tutorial,warnings}/*.md"
}
```

And we can put rule files directly under the `textlint` directory.

**Comment by potato4d** [comment]
一旦第一段階はできたとして、クローズしておきましょう！
またルールを追加する場合は、個別で！
