### ISSUE TITLE
Translate Release Channels

### ISSUE THREAD

**Issue by smikitky** [reactjs/ja.reactjs.org#275]
Original: https://reactjs.org/docs/release-channels.html

**Comment by numb86** [comment]
やりたいです。
アサインしてもらった後に作業してPRを出せばよいでしょうか？

**Comment by smikitky** [comment]
はい、助かります。よろしくお願いします。
PRをいただければレビュー→マージ、という流れになります。

別の記事との兼ね合いがあるため experimental build は「実験的ビルド」でお願いします。
他のルールは TRANSLATION.md を参照ください。

**Comment by numb86** [comment]
ありがとうございます。

早速ですが、相談があります。

現在、textlint で「箇条書きの文末に句点(。)を付けるかを統一します。」というルールが有効になっています。
原文に沿って翻訳すると、15行目から始まるリストと52行目から始まるリストが、このルールに引っ掛かってしまいます。
前者は`**`で終わる行があるため、後者はリストのなかでコードブロックを使っているため、です。

このエラーを回避しようとすると、「textlint のエラーを回避するために原文との乖離が大きくなる」という状況が発生してしまいます。
特に52行目から始まるリストの場合、「リストのなかにコードブロックがある」という文書構造自体を変えることになります。

これは望ましくないように思えるので、部分的に textlint のルールを無視できるようにするために [textlint-filter-rule-comments](https://github.com/textlint/textlint-filter-rule-comments) を導入しようと思うのですが、どうでしょうか。

**Comment by smikitky** [comment]
@numb86 そのルールはしょっちゅう間違ったエラーを出してくるので、個人的にはルールごと無効化してもいいのかなと思います。もしよければ、対応するルールを無効化するPRを先に出していただければ…

**Comment by smikitky** [comment]
#293 で完了
