### ISSUE TITLE
散見される`。（`の修正をしてもよいでしょうか。

### ISSUE THREAD

**Issue by kobaji** [reactjs/ja.reactjs.org#376]
初投稿です。Reactの勉強をしていて読みづらい箇所を見つけ、以下を修正したいです。

https://github.com/reactjs/ja.reactjs.org/blob/master/content/home/examples/a-stateful-component.md#7 などで、不適切な`。（`の使われ方をしているように見えます。

> できます。（これは `this.state` で参照することができます）状態

これは、「できます（これは `this.state` で参照することができます）。状態」が適切だと思われます(事実英語では`xxx(xxx).xxx`なっています)。これを修正したいですがよろしいでしょうか。<br>

masterブランチに対して`。（`でGREPすると35件ヒットし、そのうちのいくつかは同様に修正したいですがいかがでしょうか。

**Comment by smikitky** [comment]
うろ覚えなのですが、日本語のミスを減らすために導入したはずの textlint のJTFプラグインの過剰検出のため、仕方なくこうなっていたような気がします。

`git commit .`しようとすると自動で textlint が走ってエラーが出るはずですので、試しに1カ所修正してコミットしてみて普通にコミット可能かどうか確認していただいても良いでしょうか。以下のファイルが設定なので、そこで単純に検出オプションを1個無効にする程度で済めばそのようにするのが良いと思います。

https://github.com/reactjs/ja.reactjs.org/blob/master/.textlintrc

**Comment by kobaji** [comment]
ご連絡ありがとうございます。年が明けたらトライしてみます。

**Comment by kobaji** [comment]
@smikitky さんの予想とは異なり、`git commit`してもエラーが起こりませんでした。このまま全箇所について修正をかけてもよろしいでしょうか。

詳細：
https://github.com/kobaji/ja.reactjs.org/commit/31a91ec9d70ec40bfbae00648fa5b39e6c8bbe60
.textlintrc を変更せず、`（）。`の使い方を1ヶ所修正してみました。特にエラーは出ていないようですね。
yarnのテストも行なってみようと思いましたが、ネットワークの都合でYarnのインストールができずテストできていません。

**Comment by smikitky** [comment]
はい、では修正していただいて大丈夫です。お手数をおかけします。
