### ISSUE TITLE
ReactDOM.render() と ReactDOM.hydrate() の扱い

### ISSUE THREAD

**Issue by mendelssohnbach** [reactjs/ja.reactjs.org#384]
Reactの学習を始めたばかりの初心者です。

Reactが「既存のプロジェクトに徐々に追加可能」であることは読みました。

[Hello World](https://ja.reactjs.org/docs/hello-world.html)

`ReactDOM.render` が使われています。解説の通りの結果を得ました。

しかし、[リファレンス](https://ja.reactjs.org/docs/react-dom.html#reference) の補足に

> ReactDOM.render() を使用することは非推奨となり、React 17 では削除されます。

とあります。

多くの初心者が公式サイトで学ぶと考えます。

[Hello World](https://ja.reactjs.org/docs/hello-world.html) から [リファレンス](https://ja.reactjs.org/docs/react-dom.html#reference) へリンクを貼っておくことが重要だと考えます。

**Comment by smikitky** [comment]
そのリファレンスで言及されているのは、サーバサイドレンダリング (SSR) というテクニックの話です。`ReactDOM.render()` 自体が使えなくなるという話ではありません。

> **サーバで描画されたコンテナをクライアントで再利用するために** ReactDOM.render() を使用することは非推奨となり、React 17 では削除されます。代わりに hydrate() を使用してください。

SSR自体がやや上級者向けの話であり、少なくとも Hello World で触れるようなものではありません。SSR を使わずにブラウザで動くアプリを書く場合、`ReactDOM.render()` を使い続けて全く問題ありません。

（まあ、将来的に並列モードがデフォルトになると書き方がまた微妙に[変わる](https://ja.reactjs.org/docs/concurrent-mode-adoption.html#migration-step-blocking-mode)のですが…）

**Comment by mendelssohnbach** [comment]
お忙しい中、回答ありがとうございます。

> ReactDOM.render() を使い続けて全く問題ありません。

わかりました。
いただいたリンクを読んで未来に備えておきます。

2021年2月9日(火) 14:03 Soichiro Miki <notifications@github.com>:
