### ISSUE TITLE
並列 vs 並行 for "concurrency"

### ISSUE THREAD

**Issue by smikitky** [reactjs/ja.reactjs.org#422]
以前 Twitter か何かで「concurrent modeは『並列モード』ではなく『並行モード』が正しい」みたいな指摘を見たことがあり、当時はあまり気に留めていなかったのですが、ふと違いがあるのか気になって調べてみたところ、どうも確かに「並行」の方が正しいのではという気がしてきました。

Wikipedia を見た限り、両者は学術的に違う概念であり、以下のように区別されると理解しました。

- [並列](https://ja.wikipedia.org/wiki/%E4%B8%A6%E5%88%97%E8%A8%88%E7%AE%97) = parallel = 複数のプロセッサで大きなタスクを分散処理して処理時間を短縮すること。みんなで手分けして作業すればつらい仕事も早く終わる、的なこと。
- [並行](https://ja.wikipedia.org/wiki/%E4%B8%A6%E8%A1%8C%E8%A8%88%E7%AE%97) = concurrent = （1コア内で）スレッドのスケジューリングや non-blocking IO、Promise.all 的なものを使い、応答性を改善すること（合計処理時間は減らなくてもよい）。1人しかいないけどひとまず同時に多数の仕事に着手してそれぞれ少しずつ作業を進めていれば文句が出ない、的なこと。

[【小ネタ】並列処理とは何か？そして並列処理と並行処理の違いとは？](https://qiita.com/4_mio_11/items/7f418ca661d9f5a2a39d)

というわけで、React の concurrency は別に Web Worker を使った高速化みたいな話ではないので、「並行」の方が学術的に正しい気がしてきました。幾何学の「**平**行」が「parallel」なので混乱していました…。

次回ドキュメント刷新のあたりでこっそり「並行」に変えるのがいいのかなと思っているのですが、如何でしょうか。

**Comment by koba04** [comment]
👍 いいと思います！確かに React のやっていることを考えても並行ですね。（日本語での違いをあまり意識してませんでした...）

**Comment by koba04** [comment]
@smikitky  こちらは #423 で close されたということで大丈夫でしょうか？

**Comment by smikitky** [comment]
はい、大丈夫です
