### ISSUE TITLE
Improve translation guideline

### ISSUE THREAD

**Issue by potato4d** [reactjs/ja.reactjs.org#95]
@smikitky @koba04 

ちょっと翻訳ガイドラインとフローの改善について提案させてください。

- - -

現在、レビュアー↔レビュアー間・ Pull Request 発行者↔レビュアー間での「翻訳改善」についての議論が白熱しがちな傾向にあると思います。

これは、より良いドキュメントを作るためには不可欠であるものの、その一方で「Must to have」と「Nice to have」が分かりづらくなっており、翻訳者としても誰のオピニオンを重要視すべきかという点で負担になってしまっている様子が見受けられます。

この問題を解消するため、以下の二点を提案したいと思います。

## レビューコメントの prefix の必須化

レビューコメントに以下の prefix を必須化したいと思います。

- must: 必ず修正しなければいけない内容
- want: 改善点が見受けられる内容
- imo: レビュアー観点で改善点があり、かつ対案が出せる内容
- nits: 細かなやってもやらなくても良い対応

その上で、 **必ず治すものは must に限定** し、その他については翻訳者側の意見を取り入れたいと思います。レビュアー観点で **必ず** というものは遠慮なく must を、逆に議論の種になるものは want や imo をつけていきます。

そうすることで、よりよい翻訳を目指しながらも、かつ翻訳者の裁量に合わせる事ができるかと思います。品質とスピード感、貢献意欲のある翻訳者のモチベーション全てを一定以上に両立するためです。

## 翻訳度のサンプル整備

また、「どこまで読みやすくするか」言い換えれば、「どこまで意訳にするか」の翻訳度も議論の種になっているように見えます。

そして、それはおそらく TRANSLATION.md の以下の項の抽象度の高さによって生まれていると考えています。

> 英文から飛躍した意訳や表現の追加・改変を行わない。一方で分かりづらくなるような逐語訳もしない。

ここについて、メンテナおよびレビュアー視点でいくつかサンプルを追加するのはいかがでしょうか？

どの程度まで意訳し、どの程度まで直訳するかのサンプルを設けることが、品質の平坦化につながると思います。

### 余談

Vue.js JP の場合は原則一語一訳の直訳が取られていますが、フローが統一化される反面、多少読みづらさが出る部分もあるので、ここは React の現在のものをベースに考えるのが良い形だと考えています。

https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md#%E5%8E%9F%E5%89%87%E4%B8%80%E8%AA%9E%E4%B8%80%E5%8F%A5%E7%BF%BB%E8%A8%B3%E3%81%9F%E3%81%A0%E6%97%A5%E6%9C%AC%E8%AA%9E%E3%81%A8%E3%81%97%E3%81%A6%E5%88%86%E3%81%8B%E3%82%8A%E3%81%AB%E3%81%8F%E3%81%84%E5%A0%B4%E5%90%88%E3%81%AF%E8%AA%AD%E3%81%BF%E3%82%84%E3%81%99%E3%81%95%E3%82%92%E5%84%AA%E5%85%88

**Comment by potato4d** [comment]
@takanorip
write 権限所有者からは外れますが、比較的多くのドキュメントにレビューいただいているかと思いますので、もし何か案などがあればこちらに追記していただければと思います :pray:

**Comment by potato4d** [comment]
ファーストレビュー後、追加レビューで議論になることもあると思いますが、そこまで多くはないと思うので、ひとまず prefix 案は「初回レビュアーが一通り must かそれ以外かを判断しきってから進む」という前提の感覚値でいます。

**Comment by smikitky** [comment]
なんとなく、must は波風立てる悪影響の方が大きい気がします（既に must と明記されたものに反駁した記憶もありますし）。
基本的に、「どうでもいいんだけどこうした方がもうちょっといいのでは」くらいのノリで書いたもので不快感を与えるのがよろしくないようなので、そういう気持ちをちゃんと明示できれば…というのは反省点としてもあります。

**Comment by takanorip** [comment]
レビュワーが必ず正しいというわけでもなく、どのレビューにも議論の余地があると思うの で`must` は少し押しつけ感が強いかなと思いました。
基本的には翻訳者の
個人的には、 `must` `want` などの言葉ではなく「重要度：1」のような段階で示せたら良いかもと思います。

**Comment by smikitky** [comment]
翻訳サンプルの件ですが、いわゆる大学受験対策で出てきそうな典型的な物主構文の話などは全員とてもよく対応できているので、これ以上のレベルをとなると例示で示すのは厳しいかもしれません。

（トップページのは例外で、普通なら全く正しい訳を、私が短さやキャッチ―さ優先でニュアンスを切り捨てまくった上に、よく意図を説明しなかったのが原因です）

**Comment by koba04** [comment]
難しいですね...。
Suggestion機能が便利で、カジュアルにSuggestionしてしまっているので、確かに指摘ではなく提案であることをimoとして明示した方がいいかなとは思いました。
